### ISSUE TITLE
Can't connect to SOCKS proxy:http

### ISSUE THREAD

**Issue by cxplonka** [Wisser/Jailer#8] opened 2018-07-06 06:47 UTC
Hi,

since Jailer 7.10 i have currently a problem when i want connect to remote databases. Jailer say that he can not connect to the DB, before 7.10 everything works fine. How can i solve this problem?

![image](https://user-images.githubusercontent.com/13945224/42363619-94ac1a0a-80f8-11e8-8853-84ed945db67c.png)

P.S. Thanks for the great product.

**Comment by Wisser** [comment] 2018-07-06 07:14
Hi,

which DBMS do you use?

**Comment by Wisser** [comment] 2018-07-06 07:35
Since 7.10 the system property "java.net.useSystemProxies" is set to true. That's most probably the cause of the problem.
Would you please try the attached patch? (replace the file "jailer.jar" with the one in the attached zip file)
It resets the property to the default value.

HTH,
Ralf

[jailer_patch.zip](https://github.com/Wisser/Jailer/files/2169408/jailer_patch.zip)

**Comment by cxplonka** [comment] 2018-07-06 07:52
The patch not solve the problem. 
I take the jailer.jar from 7.9.4 and everything works fine but with >= 7.10 or your patch it will not connect.

DBMS is Oracle 12

**Comment by Wisser** [comment] 2018-07-06 07:58
Thanks for trying the patch. Would you please do the same with this:
[jailer_patch2.zip](https://github.com/Wisser/Jailer/files/2169498/jailer_patch2.zip)

**Comment by cxplonka** [comment] 2018-07-06 08:00
Sorry, not work. Only localhost work.

**Comment by Wisser** [comment] 2018-07-06 08:03
Sorry, the latest patch has still set the property. I hope this one works:
[jailer_patch3.zip](https://github.com/Wisser/Jailer/files/2169516/jailer_patch3.zip)

**Comment by cxplonka** [comment] 2018-07-06 08:06
Thanks, now it works.

**Comment by Wisser** [comment] 2018-07-06 08:15
Thanks for reporting and testing the patches. The issue will be fixed in the next release.

**Closed** 2018-07-06 08:18 UTC
